name: Deploy

on:
  push:
    branches:
      - main

jobs:
  list_applications:
    name: List application files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          mkdir applications
          for file in $(ls files/applications/*.yaml); do cat $file | envsubst > applications/"${file##*/}" ; done
          echo $(ls applications/*.yaml | jq -R -s -c 'split("\n")[:-1]')
          ls applications
          echo "::set-output name=matrix::$(ls applications/*.yaml | jq -R -s -c 'split("\n")[:-1]')"

  deploy_applications:
    needs: list_applications
    strategy:
      matrix:
        application: ${{ fromJson(needs.list_applications.outputs.matrix )}}
    name: Deploy applications
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          ${{secrets.INVENTORY}}
        requirements: requirements.yaml
        options:
          --extra-vars ${{ matrix.application }}
