name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_application:
    name: Deploy application
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a copy of the file
        run: |
          mkdir applications
          for file in *.yml *.yaml; do cat $file | envsubst > applications/$file ; done
      - id: matrix
        run: |
          for file in applications/*.yml applications/*.yaml; do $file ; done

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: ./
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          ${{secrets.INVENTORY}}
        requirements: requirements.yaml
        options:
          --extra-vars @applications/
